from setuptools import find_packages, setup

setup(
    name='src',
    packages=find_packages(),
    version='0.1.0',
    description=' Python tool for conversational queries on multiple PDFs using natural language. Responses generated by a language model, limited to loaded PDF content.',
    author='Shubham Aware',
    license='',
)
